### ISSUE TITLE
UseLoader colliding with Suspense in ModelViewPage.tsx

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [opensim-org/opensim-viewer#107]
In ModelViewPage.tsx, we use useLoader to load the floor texture, and then there is a Suspense around the canvas.

UseLoader is synchronous, while Suspense expects all operations performed inside (or operations it depends of) to be asynchronous.

We need to find a way of loading the floor texture in an asynchronous way.

**Comment by aymanhab** [comment]
Should be fixed by #109
