### ISSUE TITLE
Rearrange front end for usability

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-viewer#132]
Items include:

- [x] Remove measure/ruler button from bottom bar
- [x] wire the annotation [A] button to display textual name somewhere
- [x] Move animation button/slider from side-toolbar to bottom.
- [x] make animation slider and control more accessible so a viewer without side-toolbar are functional reducing footprint

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz in case you're interested in any of these

**Comment by AlbertoCasasOrtiz** [comment]
I just self assigned this, I will take care of it after the winter break!

**Comment by AlbertoCasasOrtiz** [comment]
I just self assigned this, I will take care of it after the winter break!

**Comment by AlbertoCasasOrtiz** [comment]
Hi @aymanhab, I don't undestand the second point. Should it display the textual name of the model somewhere?

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz I think we should have an (i) icon somewhere in the ui that expands to the info: Model, publication, simulation settings that we can embed-into/extract-from the gltf as we discussed earlier for #141 

Separately, objects have names as seen on the scene tree, if we can have a fixed, readonly text box somewhere on the screen showing what's selected without needing to expand the side panel that would be great. Not entirely clear on how it looks like but maybe the annotation button is a toggle that opens a small panel with the textbox, or a selected:xxx textbox in bottom bar. Thoughts?

**Comment by AlbertoCasasOrtiz** [comment]
Sure, I am working on the (i) icon and I have already a floating icon that shows a floating window (empty for now) when clicked. I'll have it soon showing the model information.

**Comment by AlbertoCasasOrtiz** [comment]
Hi @aymanhab, I think this is finished. The main changes are:

The animation controls are now in the bottom bar.
Removed animation tab from side bar.
Removed speed.
Added info tooltip at top right (not populated until we have metadata in the gltf)

Let me know if I forgot something or something is not right.
