### ISSUE TITLE
Wire jupyter notebooks to visualization

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-viewer#135]
Some groundwork is needed to enable conversion to gltf format in a notebook and uploading to s3 then show an IFrame with the url of the gltf files.

**Comment by aymanhab** [comment]
There're two steps to wire visualization to jupyter notebooks:
1. Create a gltf from the current model and/or dataset
2. launch the viewer with a url for the gltf file produced in step 1.
@aymanhab will take on step 1 as there's code already there to do this on the back end, and will provide the logistics to run it in jupyter while @AlbertoCasasOrtiz  will handle step 2 which primarily deals with authentication, and/or uploading the files to an s3 bucket temporarily.

**Comment by aymanhab** [comment]
There's now a notebook that creates the gltf from a model file under the contents folder.
https://github.com/opensim-org/opensim-models/blob/vizualization/notebooks/tutorials/Tutorial%201%20-%20Set%20up%20OpenSim%20With%20Viz%20in%20Google%20Colab.ipynb

Please let me know @AlbertoCasasOrtiz if you have any questions on how to proceed. The source being used is a separate repository that contains python scripts, wrapper and the Geometry files which is the same code used for the aws backend.
https://github.com/opensim-org/opensim-viewer-backend

**Comment by AlbertoCasasOrtiz** [comment]
A working version that requires to download the file locally and then select it inside of the viewer (which is an Iframe inside of the notebook) can be found here:

https://colab.research.google.com/drive/1WdoXOCnygegddK8mDFVeNOC-IdZDqVnO?usp=sharing

Next steps: Explore the use of drive and passing the link of the file to the viewer's url to avoid the step of downloading the file.

**Comment by AlbertoCasasOrtiz** [comment]
Hi Ayman, with the latest deployment to dev in #162 this should work. Now the top and left bars in the visualizer are not shown if you add the parameter ?css=gui to the URL.

The only remaining problem is that you have to download the generated gltf file and then load it again in the framed visualizer.
