### ISSUE TITLE
Populate the model-list grid with existing published models

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-viewer#20]
This involves exporting models to gltf format using current GUI, for now we'll use a json array to map models to gltf files, populate grid-element with reference to publications and/or confluence page(s)

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz when you have time we can discuss what's involved here

**Comment by AlbertoCasasOrtiz** [comment]
I have a first draft for this in this PR: https://github.com/opensim-org/opensim-viewer/pull/25.
