### ISSUE TITLE
Adjust colors and logo to switching themes

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-viewer#21]
Adjust canvas background colors, logo-colors depending on dark/light theme. As of now switchable using the 'd' key-stroke. May move to settings later.

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz we can discuss when you have cycles

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab I've been testing colors for the upper bar and I think the main problem is that in the opensim logo inlight mode, there is a lot of contrast between the blue tone and the black tone, so if you try to set a lighter color there is not enough contrast with the blue tone, and if you try a darker color there is no contrast with the black tone.

Do you any ideas of what we could do here?
