### ISSUE TITLE
Shorten AppBar for smaller screens

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-viewer#33]
As of now AppBar overflows on small screens/phones, ideas for improvement discussed here
https://github.com/opensim-org/opensim-viewer/pull/32/

**Comment by AlbertoCasasOrtiz** [comment]
Ideas we had last week:
 - Use a variant of OpenSim icon without text for small devices.
 - Change buttons "Viewer" and "Models" by icons in small devices.
 - Create additional vertical bar for this.
 - Create a collapsible top or lateral menu: https://mui.com/material-ui/react-drawer/
