### ISSUE TITLE
Create notebooks for visualization utilities for independent use outside viewer

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-viewer#46]

**Comment by AlbertoCasasOrtiz** [comment]
I have a first version for this working in colab. I am going to make it more user friendly and create a PR soon.

**Comment by AlbertoCasasOrtiz** [comment]
Hi @aymanhab. I just created the interactive colab notebook. No need to insert or modify code, just to set parameters and click a few buttons: https://colab.research.google.com/drive/1x2uhlbXs6ONVgx-biMPAVtvOg_gTxVAu?usp=sharing

Maybe we can simplify it a little more and add more feedback to the user.

**Comment by AlbertoCasasOrtiz** [comment]
Where should I upload the notebook?
