### ISSUE TITLE
Create django backend

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [opensim-org/opensim-viewer#53]
This will provide of a basic API in which users can create an User and upload models, that can later be downloaded and shown in the frontend. Once this is finished, we only have to connect the frontend.

- [x] [Environment Creation with YML file](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html).
- [x] Use of [Django Rest Framework](https://www.django-rest-framework.org/).
- [x] Method to Create [ERD Diagrams](https://www.wplogout.com/export-database-diagrams-erd-from-django/) of the database.
- [x] Definition of User.
- [x] Definition of Model.
- [x] [Admin Page Customization](https://realpython.com/customize-django-admin-python/#customizing-the-django-admin).
- [x] API Method to List Users.
- [x] API Method to List Models.
- [x] API Method to Create Users.
- [x] API Method to Create Models.
- [x] API Method to Retrieve Models.
- [x] [Add .gitignore file](https://djangowaves.com/tips-tricks/gitignore-for-a-django-project/).
- [x] [API testing](https://www.django-rest-framework.org/api-guide/testing/).
- [x] [Internationalization/localization](https://phrase.com/blog/posts/quick-guide-django-i18n/). (Before error handling, so error messages can directly be implemented using i18n).
- [x] [Error handling](https://www.django-rest-framework.org/api-guide/exceptions/).
- [x] [Generate documentation](https://docs.djangoproject.com/en/4.2/ref/contrib/admin/admindocs/).
- [x] Create readme.md file with setup instructions.

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab Should I create a new repository for the django backend?

As soon as I finish with the remaining items I will upload everything. I think the [Internationalization/localization](https://phrase.com/blog/posts/quick-guide-django-i18n/), [API testing](https://www.django-rest-framework.org/api-guide/testing/) and [Generate documentation](https://docs.djangoproject.com/en/4.2/ref/contrib/admin/admindocs/) items could take some time since it is something I have never done in django before.

Right now I am running everything locally, so we can easily test and connect with the frontend.

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz Is it possible to use the backend folder I created in this PR https://github.com/opensim-org/opensim-viewer/pull/54
I read some discussion regarding using 2 separate repos but seemed an overkill in this case especially that the backend is rather thin though I'm open to be convinced otherwise

**Comment by AlbertoCasasOrtiz** [comment]
The backend right now is very small and I don't think it will grow too much, so I agree. I'll upload to the backend folder then.

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab Since I had some problems uploading it, I have uploaded everything to a [new repo in my account](https://github.com/AlbertoCasasOrtiz/opensim-viewer-server/), so everything is backed up. Next week first thing I'll do is to fix it and upload it to the backend folder in the opensim-viewer repo.
