### ISSUE TITLE
Run backend in docker container

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-viewer#83]
While we can run the backend natively, using docker will be better long term for separation of responsibility and to avoid hiccups when we deploy on a cloud server likely running Linux

**Comment by AlbertoCasasOrtiz** [comment]
I agree. At some point, when we are ready to deploy on a cloud server, it could also be useful to take a look at terraform and amplify. This is what we use on Opencap (and addbiomechanics I think) for deployment to AWS with docker.
